name: Test, build and publish
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pscommand: [pwsh]
        include:
          - os: windows-latest
            pscommand: powershell
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: ${{ matrix.pscommand }} -Command "Invoke-Build -File .\src\Arquebuse.build.ps1"
  buid:
    name: Build package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable
  publish:
    name: Publish package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable