name: Test, build and publish
on: [push, pull_request]
jobs:
  test:
    name: Run Tests on different OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        shell: [pwsh]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - shell: powershell
            os: windows-latest
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
      with:
         shell: ${{ matrix.shell }}
    - name: Display the path
      run: echo ${env:PATH}
    - name: Version Display
      run: $PSVersionTable
    - name: Bootstrap
      run: ./actions_bootstrap.ps1
    - name: Test
      run: Invoke-Build -File .\src\Arquebuse.build.ps1
  buid:
    name: Build package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable
  publish:
    name: Build package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable